### ISSUE TITLE
ValueError: Format 'jpg' is not supported (supported formats: eps, pdf, pgf, png, ps, raw, rgba, svg, svgz)

### ISSUE THREAD

**Issue by AnanthuPS** [cleardusk/3DDFA#137]
While running main.py , I got this eerror ----

ananthu@ananthu-Z390-M:~/Downloads/3DDFA-master$ python3 main.py -f samples/emma_input.jpg
Dump tp samples/emma_input_0.ply
Save 68 3d landmarks to samples/emma_input_0.txt
Dump obj with sampled texture to samples/emma_input_0.obj
Dump tp samples/emma_input_1.ply
Save 68 3d landmarks to samples/emma_input_1.txt
Dump obj with sampled texture to samples/emma_input_1.obj
Dump to samples/emma_input_pose.jpg
Dump to samples/emma_input_depth.png
Dump to samples/emma_input_pncc.png
Traceback (most recent call last):
  File "main.py", line 205, in <module>
    main(args)
  File "main.py", line 177, in main
    draw_landmarks(img_ori, pts_res, wfp=img_fp.replace(suffix, '_3DDFA.jpg'), show_flg=args.show_flg)
  File "/home/ananthu/Downloads/3DDFA-master/utils/inference.py", line 189, in draw_landmarks
    plt.savefig(wfp, dpi=200)
  File "/home/ananthu/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/ananthu/.local/lib/python3.6/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/ananthu/.local/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 94, in print_figure
    super().print_figure(*args, **kwargs)
  File "/home/ananthu/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2021, in print_figure
    canvas = self._get_output_canvas(format)
  File "/home/ananthu/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1963, in _get_output_canvas
    .format(fmt, ", ".join(sorted(self.get_supported_filetypes()))))
ValueError: Format 'jpg' is not supported (supported formats: eps, pdf, pgf, png, ps, raw, rgba, svg, svgz)

Thanks in advance....

**Comment by g2ragrawal** [comment]
maybe this problem is occur due too pillow version
you can check [here](https://github.com/matplotlib/matplotlib/issues/16083)

**Comment by cleardusk** [comment]
You may try updating your matplotlib or referring to g2ragrawal. matplotlib is just for visualization, you can also use cv(opencv) to visualize it.

**Comment by Mandyrose** [comment]
Hi cleardusk,
I have the same problem, updating matplotlib didn't help.
could you explain how to use opencv in that case? what should I change?

thanks

**Comment by cleardusk** [comment]
Sorry for that I can not re-implement your status : (

**Comment by g2ragrawal** [comment]
@Mandyrose  use opencv for reading and writing images may be in some place you have to change bgr to rgb.
